language: python
env:
  global:
  - PYTHON=python
  - PIP=pip
  - SETUPTOOLS_SCM_PRETEND_VERSION=$TRAVIS_TAG
  - MAKE=make
matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    env: 
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
      - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64

  - os: osx
    language: generic
    osx_image: xcode8.3
    env: PYTHON=python3 PIP=pip3
  - os: windows
    language: bash
    env: PATH=/C/Python37:/C/Python37/Scripts:$PATH
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y python ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade python3 ; fi
- if [ "$TRAVIS_OS_NAME" = "linux"]; then docker pull $DOCKER_IMAGE ; fi
script:
- "./build.sh init"
- "./build.sh build"
- "./build.sh test"
- if [ "$TRAVIS_OS_NAME" = "linux"]; then ./build.sh manylinux ; fi
- ls -l dist/unrar*cffi*manylinux*.whl
- ls -l dist/unrar*cffi*.tar.gz

branches:
  only:
  - develop
  - "/^v\\d.*/"